apiVersion: v1
kind: Service
metadata:
  name: devops-agent
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devops-agent
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
      nodePort: 30090